[package]
name = "triedb"
version = "0.5.0"
edition = "2018"
license = "Apache-2.0"
description = "Lightweight Ethereum world state storage."
repository = "https://github.com/hrls/triedb"

[lib]
name = "triedb"

[features]
default = []
rocksdb = ["rocksdb_lib"]

[dependencies]
sha3 = "0.6"
rlp = "0.5.0"
thiserror = "1.0.23"
primitive-types = { version = "0.9.0", features = ["rlp"] }
rocksdb_lib = { package = "rocksdb", version = "0.15.0", default-features = false, optional = true }

[dev-dependencies]
etcommon-hexutil = "0.2"
