[package]
name = "etcommon-trie"
version = "0.3.3"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Lightweight Ethereum world state storage."
repository = "https://github.com/ethereumproject/etcommon-rs"

[lib]
name = "trie"

[dependencies]
etcommon-bigint = { version = "0.2", path = "../bigint" }
etcommon-rlp = { version = "0.2", path = "../rlp" }
sha3 = "0.6"

[dev-dependencies]
etcommon-hexutil = "0.2"