[package]
name = "triedb"
version = "0.5.0"
edition = "2018"
license = "Apache-2.0"
description = "Lightweight Ethereum world state storage."
repository = "https://github.com/hrls/triedb"

[lib]
name = "triedb"

[dependencies]
sha3 = "0.6"
rlp = "0.5.0"
primitive-types = { version = "0.9.0", features = ["rlp"] }
thiserror = "1.0.23"


[dev-dependencies]
etcommon-hexutil = "0.2"
