[package]
name = "etcommon-trie"
version = "0.2.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Lightweight Ethereum world state storage."
repository = "https://github.com/ethereumproject/etcommon"

[lib]
name = "trie"

[dependencies]
etcommon-bigint = "0.2"
etcommon-rlp = "0.2"
sha3 = "0.6"

[dev-dependencies]
etcommon-hexutil = "0.2"